### ISSUE TITLE
Casting shadows.

### ISSUE THREAD

**Issue by sairam4123** [SIsilicon/Godot-Volumetrics-Plugin#10]
Is it possible to cast shadows to Terrain? I'm looking for a way to make clouds while casting shadows as well.
Thanks for this awesome addon!

**Comment by SIsilicon** [comment]
As of now, volumes can only cast shadows on themselves as long as they're in view.
I wouldn't recommend using this plug-in for atmospheric clouds though, it's best suited for fog that's relatively close to the viewer.

**Comment by SIsilicon** [comment]
What most games do is render the clouds with a raymarcher, and fake the shadows with some sort of shadow proxy.
But if you want a more realistic solution, I unfortunately do not know any cloud add-on that casts faux shadows at the moment. You could look for a cloud add-on repo, and make a feature request there instead.

**Comment by sairam4123** [comment]
Alrighty thanks!
