### ISSUE TITLE
[BUG] Volumetric server

### ISSUE THREAD

**Issue by nonunknown** [SIsilicon/Godot-Volumetrics-Plugin#3]
Installed the plugin and got this issue:

![Screenshot from 2020-04-11 08-50-55](https://user-images.githubusercontent.com/58845030/79042874-ada6ea00-7bd1-11ea-8662-42946f8b7f4b.png)

PS: Downloaded from asset store

**Comment by SIsilicon** [comment]
You have installed version 1.0. The asset library hasn't been updated yet so you should download 1.0.1 [here](https://github.com/SIsilicon/Godot-Volumetrics-Plugin/archive/v1.0.1.zip).

**Comment by nonunknown** [comment]
I've downloaded from master branch, and got the same error.

**Comment by SIsilicon** [comment]
You got that exact same error you're showing at the start? The one with
`The identifier 'VolumetricServer' isn't declared in the current scope` in that script?

**Comment by SIsilicon** [comment]
I'm asking 'cause that specific error has already been fixed in the master branch. Are you sure you are running the right version?

**Comment by nonunknown** [comment]
I'll try downloading from your link, on a clean project

**Comment by nonunknown** [comment]
Downloaded from link you've passed and just opened your demo scene: 
![Screenshot from 2020-04-11 09-52-41](https://user-images.githubusercontent.com/58845030/79044200-45a8d180-7bda-11ea-8c13-c395681eb21c.png)

changing **preload** to **load** makes the plugin works flawlessly

**Comment by SIsilicon** [comment]
Alrighty! Could you change that string to "test_volume.png" and keep it preloaded. It should keep the fog textures that way.

**Comment by SIsilicon** [comment]
Thanks for discovering that bug in particular though. The plugin's been updated to include that fix.
