### ISSUE TITLE
Volumetrics overlay not working in editor viewport (3.2.1-stable)

### ISSUE THREAD

**Issue by lonegamedev** [SIsilicon/Godot-Volumetrics-Plugin#4]
I have encountered a problem when using a non-default name_casing in project settings.
What is strange only editor viewport is affected, after starting any scene the volumetrics work.

This might be a problem with Godot itself, but for anyone who experiences this, the temp solution is to change name_casing to default "PascalCase" under ProjectSettings, and restart Godot.

These errors are echoed before running any scene:

`ERROR: Node not found: LightScatter.
   At: scene\main\node.cpp:1381
ERROR: ViewportTexture: Path to node is invalid.
   At: scene\main\viewport.cpp:69
ERROR: Node not found: LightTransmit.
   At: scene\main\node.cpp:1381
ERROR: ViewportTexture: Path to node is invalid.
   At: scene\main\viewport.cpp:69
ERROR: Node not found: .
   At: scene\main\node.cpp:1381
ERROR: ViewportTexture: Path to node is invalid.
   At: scene\main\viewport.cpp:69`

**Comment by SIsilicon** [comment]
As stated in the [README file](https://github.com/SIsilicon/Godot-Volumetrics-Plugin#installation), the errors you are showing above are normal and do not affect the project's performance.
As for the name casing, could you elaborate more on that? I can't seem to find it in neither the project nor editor settings.

**Comment by SIsilicon** [comment]
I'll just close this for now.
