### ISSUE TITLE
plugin broken on 3.2.2

### ISSUE THREAD

**Issue by tastesliketriangle** [SIsilicon/Godot-Volumetrics-Plugin#5]
tried on a custom build of the 3.2.3.rc but it didn't work. tried the demo project using 3.2.2 64x off the website but this doesn't work either. the scripts produce errors in the editor and in game.

`
res://addons/silicon.vfx.volumetrics/volumetric_server.gd:199 - Invalid get index 'camera' (on base: 'Node (volumetric_renderer.gd)').
`

this pops up every frame in the editor. which makes it hard to copy the other errors, other than by hand. the other errors include defining already existing variables, assigning nil values to integers, "nonexistant func 'add_light' in base 'node'".

**Comment by SIsilicon** [comment]
Thanks for letting me know! I'll look into it tomorrow. 😊

**Comment by SIsilicon** [comment]
Good afternoon! I made an attempt to fix the issue. Could you please test the latest change to see if it solved your issue?

**Comment by tastesliketriangle** [comment]
It fixed the spam and let me run the demo. But I still get errors.

`
Invalid get index 'coords' (on base: 'Dictionary').
`
At several points.
![image](https://user-images.githubusercontent.com/5613717/89461144-6f61a780-d739-11ea-9b9c-cd96bd6767d6.png)

**Comment by SIsilicon** [comment]
Ok, I'll look into that.

**Comment by tastesliketriangle** [comment]
It should be noted that the errors only happen when close to and facing the two light sources in the corners of the room. At least in the example project. I'll need time to see how it behaves in my own projects.

**Comment by SIsilicon** [comment]
Sorry for the wait! It should be fine now. 😅
