### ISSUE TITLE
Volume doesn't render when under viewport node

### ISSUE THREAD

**Issue by benjarmstrong** [SIsilicon/Godot-Volumetrics-Plugin#6]
When fog is placed under a viewport node it will not render using that viewport, and repeatedly outputs the following error:

    res://addons/silicon.vfx.volumetrics/renderer/volumetric_renderer.gd:304 - Invalid get index '24' (on base: 'Dictionary').

The index in the error changes periodically.

The 3D scene:
![Screenshot (2)](https://user-images.githubusercontent.com/8124614/90972053-3e66dc80-e559-11ea-83b7-9e07e713491a.png)

The 3D scene instanced under a viewport node:
![Screenshot (3)](https://user-images.githubusercontent.com/8124614/90972055-41fa6380-e559-11ea-905d-32109cee2aad.png)

I've made a minimal reproduction project at [https://github.com/benjarmstrong/volumetricsviewport](https://github.com/benjarmstrong/volumetricsviewport)

Tested on Godot 3.2.1-stable on Windows 10

**Comment by SIsilicon** [comment]
Thanks for reporting this. I'll look into this and let you know when I've fixed.

**Comment by benjarmstrong** [comment]
It seems to be something to do with the initialization order. If I remove the 3d scene from the viewport in the editor it works when the viewport has this script attached:

    extends Viewport
    var _added_child = false
    func _process(delta):
        if !_added_child:
            add_child(preload("3dscene.tscn").instance())
            _added_child = true

**Comment by SIsilicon** [comment]
Made an update to the plugin. You may try it again and see if it works.
However, there is now another bug where viewing any viewport without `own_world` set to false will always render the volume from its camera perspective anyway. So you should also set `own_world` to true so that it doesn't look weird in the 3D editor.

_tested in Godot 3.2.2_

**Comment by SIsilicon** [comment]
Closing this for now.
