### ISSUE TITLE
Can't generate new VolumeProxy Material on Godot 3.2.4 (beta 4)

### ISSUE THREAD

**Issue by DrMandible** [SIsilicon/Godot-Volumetrics-Plugin#8]
Perhaps this will fix itself for the official release so just a heads up for a potential problem. I had to revert to 3.2.3 to generate new VolumeProxy Materials.

**Comment by FeralBytes** [comment]
3.2.4 RC3 is able to generate the Volume Proxy Materials.

**Comment by SIsilicon** [comment]
That's good to hear! Closing this now.
